version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.saas
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - ENVIRONMENT=development
      - DEBUG=True
      - DATABASE_URL=sqlite:///./latencypoison.db
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://localhost:8000
      - PORT=3000
      - WDS_SOCKET_PORT=3000
      - BROWSER=none
      - HOST=0.0.0.0
    command: npm start
    depends_on:
      - api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 